name: Update IP Lists

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update IP files with retry logic
        run: |
          update_file () {
            URL=$1
            FILE=$2
            TEMP="${FILE}.new"

            echo "Updating $FILE from $URL"

            for i in 1 2 3; do
              echo "Attempt $i..."
              if curl -fsSL --connect-timeout 15 --max-time 60 "$URL" -o "$TEMP"; then
                if [ -s "$TEMP" ]; then
                  mv "$TEMP" "$FILE"
                  echo "Updated $FILE successfully"
                  return 0
                fi
              fi

              if [ "$i" -lt 3 ]; then
                echo "Retrying in 15 minutes..."
                sleep 900
              fi
            done

            echo "Failed to update $FILE. Keeping old version."
            rm -f "$TEMP"
          }

          update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=instagram.com" "inst-domains.txt"
          update_file "https://iplist.opencck.org/?format=text&data=ip4&site=instagram.com" "inst-ip.txt"   
          update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=whatsapp.com" "wa-domains.txt"          
          update_file "https://iplist.opencck.org/?format=text&data=ip4&site=whatsapp.com" "wa-ip.txt"
          update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=youtube.com" "yt-domains.txt"          
          # update_file "https://iplist.opencck.org/?format=text&data=ip4&site=youtube.com" "yt-ip.txt"
          # update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=pornhub.com&site=xhamster.com&site=xvideos.com&site=rule34.xxx" "pron-domains.txt"
          update_file "https://iplist.opencck.org/?format=text&data=ip4&site=pornhub.com" "pron-ip.txt"
          update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=rutor.info&site=rutracker.org" "rutor-rutracker-domains.txt"
          update_file "https://iplist.opencck.org/?format=text&data=ip4&site=rutor.info&site=rutracker.org" "rutor-rutracker-ip.txt"
          update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=spotify.com" "spotify-domains.txt"
          # update_file "https://iplist.opencck.org/?format=text&data=ip4&site=spotify.com" "spotify-ip.txt"
          # update_file "https://iplist.opencck.org/?format=text&data=ip4&site=telegram.org" "tg-ip.txt"
          update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=telegram.org" "tg-domains.txt"      
          update_file "https://iplist.opencck.org/?format=text&data=ip4&site=amedia.site&site=anidub.pro&site=anilibria.tv&site=animego.org&site=animevost.org&site=bato.to&site=crunchyroll.com&site=hentailib.me&site=jut.su&site=kara.su&site=kodik.info&site=mangahub.ru&site=mangapark.net&site=nyaa.land&site=nyaa.si&site=shikimori.one&site=yummyanime.tv" "anime-ip.txt"
          update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=amedia.site&site=anidub.pro&site=anilibria.tv&site=animego.org&site=animevost.org&site=bato.to&site=crunchyroll.com&site=hentailib.me&site=jut.su&site=kara.su&site=kodik.info&site=mangahub.ru&site=mangapark.net&site=nyaa.land&site=nyaa.si&site=shikimori.one&site=yummyanime.tv" "anime-domains.txt"      
          # update_file "https://beta.iplist.opencck.org/?format=text&data=cidr4&site=github.com" "github-ip.txt"
          update_file "https://beta.iplist.opencck.org/?format=text&data=domains&wildcard=1&site=github.com" "github-domains.txt"
          update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=claude.ai&site=grok.com&site=aistudio.google.com&site=canva.com&site=chatgpt.com&site=copilot&site=deepl.com&site=elevenlabs.io&site=grammarly.com&site=kilo.ai&site=perplexity.ai&site=pollo.ai" "ai-domains.txt"
          # update_file "https://iplist.opencck.org/?format=text&data=ip4&site=claude.ai&site=grok.com&site=aistudio.google.com&site=canva.com&site=chatgpt.com&site=copilot&site=deepl.com&site=elevenlabs.io&site=grammarly.com&site=kilo.ai&site=perplexity.ai&site=pollo.ai" "ai-ip.txt"
          update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=messenger.com&site=facebook.com" "fb-domains.txt"
          update_file "https://iplist.opencck.org/?format=text&data=ip4&site=messenger.com&site=facebook.com" "fb-ip.txt"
          update_file "https://iplist.opencck.org/?format=text&data=ip4&site=x.com" "x-ip.txt"
          update_file "https://iplist.opencck.org/?format=text&data=domains&wildcard=1&site=x.com" "x-domains.txt"
          update_file "https://beta.iplist.opencck.org/?format=text&data=domains&wildcard=1&site=google%40google-gemini&site=google%40google-play&site=google%40gemini&site=google%40google-registry" "ggl-domains.txt"
          update_file "https://beta.iplist.opencck.org/?format=text&data=ip4&site=google%40google-gemini&site=google%40google-play&site=google%40gemini&site=google%40google-registry" "ggl-ip.txt"
          update_file "https://beta.iplist.opencck.org/?format=text&data=ip4&site=apple%40appstore.com" "yalbaka-ip.txt"
          update_file "https://beta.iplist.opencck.org/?format=text&data=domains&wildcard=1&site=apple%40appstore.com" "yalbaka-domains.txt"


      - name: Optimize IP files
        run: |
          find . -maxdepth 1 -type f -name '*-ip.txt' \
            ! -name 'all-ip.txt' \
            ! -name 'main-ip.txt' \
            | sort \
            | while read -r f; do
                echo "Optimizing $f"
                python3 scripts/optimize_ip.py "$f"
              done

      - name: Optimize domain files
        run: |
          find . -maxdepth 1 -type f -name '*-domains.txt' \
            ! -name 'all-domains.txt' \
            ! -name 'main-domains.txt' \
            ! -name 'wa-domains.txt' \
            ! -name 'scity-domains.txt' \
            | sort \
            | while read -r f; do
                echo "Optimizing $f"
                python3 scripts/optimize_domains.py "$f"
              done

      - name: Build merged lists
        run: |
          rm -f all-ip.txt all-domains.txt

          find . -maxdepth 1 -type f -name '*-ip.txt' \
            ! -name 'all-ip.txt' \
            ! -name 'wa-ip.txt' \
            | sort \
            | while read -r f; do
                name="$(basename "$f" .txt)"
                echo "# $name" >> all-ip.txt
                grep -v '^[[:space:]]*#' "$f" >> all-ip.txt || true
                echo >> all-ip.txt
              done

          find . -maxdepth 1 -type f -name '*-domains.txt' \
            ! -name 'all-domains.txt' \
            ! -name 'scity-domains.txt' \
            ! -name 'wa-domains.txt' \
            | sort \
            | while read -r f; do
                name="$(basename "$f" .txt)"
                echo "# $name" >> all-domains.txt
                grep -v '^[[:space:]]*#' "$f" >> all-domains.txt || true
                echo >> all-domains.txt
              done

      - name: Optimize merged IP list
        run: |
          python3 scripts/optimize_ip.py all-ip.txt

      - name: Optimize merged domain list
        run: |
          python3 scripts/optimize_domains.py all-domains.txt

      - name: Commit changes if any
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add *.txt

          if ! git diff --cached --quiet; then
            git commit -m "Update IP lists"
            git push
          else
            echo "No changes detected"
          fi
